import { CalendarInfo } from '@/type/mealType';
import { FoodInfo } from '@/type/menu/menuResponse';

export const SUN_TO_SAT = ['일', '월', '화', '수', '목', '금', '토'];

export const MOCK_ALL_MENU: FoodInfo[] = [
  {
    foodId: '1',
    foodName: '쌀밥',
    kcal: 300,
    carbohydrate: 68,
    protein: 6,
    fat: 1,
  },
  {
    foodId: '2',
    foodName: '미역국',
    kcal: 50,
    carbohydrate: 10,
    protein: 3,
    fat: 2,
  },
  {
    foodId: '3',
    foodName: '불고기',
    kcal: 400,
    carbohydrate: 20,
    protein: 25,
    fat: 25,
  },
  {
    foodId: '4',
    foodName: '계란말이',
    kcal: 150,
    carbohydrate: 3,
    protein: 10,
    fat: 11,
  },
  {
    foodId: '5',
    foodName: '김치',
    kcal: 15,
    carbohydrate: 3,
    protein: 1,
    fat: 0,
  },
  {
    foodId: '6',
    foodName: '과일샐러드',
    kcal: 100,
    carbohydrate: 25,
    protein: 1,
    fat: 0,
  },
  {
    foodId: '7',
    foodName: '우유',
    kcal: 120,
    carbohydrate: 12,
    protein: 8,
    fat: 5,
  },
  {
    foodId: '8',
    foodName: '떡볶이',
    kcal: 300,
    carbohydrate: 60,
    protein: 6,
    fat: 5,
  },
  {
    foodId: '9',
    foodName: '김밥',
    kcal: 200,
    carbohydrate: 35,
    protein: 7,
    fat: 6,
  },
  {
    foodId: '10',
    foodName: '된장국',
    kcal: 70,
    carbohydrate: 6,
    protein: 4,
    fat: 3,
  },
  {
    foodId: '11',
    foodName: '감자조림',
    kcal: 150,
    carbohydrate: 30,
    protein: 3,
    fat: 4,
  },
  {
    foodId: '12',
    foodName: '닭볶음탕',
    kcal: 350,
    carbohydrate: 25,
    protein: 25,
    fat: 15,
  },
  {
    foodId: '13',
    foodName: '어묵볶음',
    kcal: 180,
    carbohydrate: 20,
    protein: 9,
    fat: 8,
  },
  {
    foodId: '14',
    foodName: '새우튀김',
    kcal: 250,
    carbohydrate: 15,
    protein: 12,
    fat: 15,
  },
  {
    foodId: '15',
    foodName: '콩나물무침',
    kcal: 50,
    carbohydrate: 7,
    protein: 3,
    fat: 1,
  },
  {
    foodId: '16',
    foodName: '잡채',
    kcal: 320,
    carbohydrate: 40,
    protein: 10,
    fat: 12,
  },
  {
    foodId: '17',
    foodName: '순두부찌개',
    kcal: 90,
    carbohydrate: 8,
    protein: 6,
    fat: 5,
  },
  {
    foodId: '18',
    foodName: '햄버거스테이크',
    kcal: 400,
    carbohydrate: 22,
    protein: 20,
    fat: 25,
  },
  {
    foodId: '19',
    foodName: '스팸구이',
    kcal: 300,
    carbohydrate: 5,
    protein: 12,
    fat: 28,
  },
  {
    foodId: '20',
    foodName: '된장찌개',
    kcal: 400,
    carbohydrate: 25,
    protein: 25,
    fat: 20,
  },
  {
    foodId: '21',
    foodName: '치킨너겟',
    kcal: 250,
    carbohydrate: 15,
    protein: 15,
    fat: 15,
  },
  {
    foodId: '22',
    foodName: '카레라이스',
    kcal: 350,
    carbohydrate: 50,
    protein: 10,
    fat: 10,
  },
  {
    foodId: '23',
    foodName: '계란찜',
    kcal: 120,
    carbohydrate: 2,
    protein: 10,
    fat: 7,
  },
  {
    foodId: '24',
    foodName: '시금치무침',
    kcal: 80,
    carbohydrate: 5,
    protein: 4,
    fat: 6,
  },
  {
    foodId: '25',
    foodName: '닭갈비',
    kcal: 350,
    carbohydrate: 30,
    protein: 20,
    fat: 18,
  },
  {
    foodId: '26',
    foodName: '김치전',
    kcal: 250,
    carbohydrate: 20,
    protein: 5,
    fat: 15,
  },
  {
    foodId: '27',
    foodName: '갈비찜',
    kcal: 450,
    carbohydrate: 25,
    protein: 20,
    fat: 30,
  },
  {
    foodId: '28',
    foodName: '부대찌개',
    kcal: 400,
    carbohydrate: 35,
    protein: 20,
    fat: 25,
  },
  {
    foodId: '29',
    foodName: '치즈버거',
    kcal: 500,
    carbohydrate: 40,
    protein: 25,
    fat: 30,
  },
  {
    foodId: '30',
    foodName: '떡국',
    kcal: 300,
    carbohydrate: 50,
    protein: 10,
    fat: 5,
  },
  {
    foodId: '31',
    foodName: '삼겹살',
    kcal: 500,
    carbohydrate: 0,
    protein: 20,
    fat: 45,
  },
  {
    foodId: '32',
    foodName: '된장국',
    kcal: 70,
    carbohydrate: 6,
    protein: 4,
    fat: 3,
  },
  {
    foodId: '33',
    foodName: '오징어볶음',
    kcal: 200,
    carbohydrate: 15,
    protein: 20,
    fat: 8,
  },
  {
    foodId: '34',
    foodName: '갈비탕',
    kcal: 350,
    carbohydrate: 20,
    protein: 25,
    fat: 20,
  },
  {
    foodId: '35',
    foodName: '김치볶음밥',
    kcal: 400,
    carbohydrate: 60,
    protein: 10,
    fat: 15,
  },
  {
    foodId: '36',
    foodName: '계란후라이',
    kcal: 90,
    carbohydrate: 1,
    protein: 6,
    fat: 7,
  },
  {
    foodId: '37',
    foodName: '오이무침',
    kcal: 40,
    carbohydrate: 6,
    protein: 2,
    fat: 1,
  },
];

export const MOCK_NEW_CALENDAR_NUTRITION: CalendarInfo = {
  '2024-10-14': {
    hospitalMenuId: 'hospital123',
    foods: [
      {
        foodId: '1',
        foodName: '쌀밥',
        kcal: 300,
        carbohydrate: 68,
        protein: 6,
        fat: 1,
      },
      {
        foodId: '2',
        foodName: '닭고기',
        kcal: 250,
        carbohydrate: 0,
        protein: 28,
        fat: 12,
      },
      {
        foodId: '3',
        foodName: '김치',
        kcal: 20,
        carbohydrate: 4,
        protein: 1,
        fat: 0,
      },
    ],
  },
  '2024-10-15': {
    hospitalMenuId: null,
    foods: [
      {
        foodId: '4',
        foodName: '떡볶이',
        kcal: 350,
        carbohydrate: 70,
        protein: 7,
        fat: 5,
      },
      {
        foodId: '5',
        foodName: '오뎅',
        kcal: 150,
        carbohydrate: 12,
        protein: 10,
        fat: 8,
      },
    ],
  },
};
