import type { Metadata } from 'next';
import './globals.css';
import Providers from '@/contexts/Providers';
import { ToastProvider } from '@/components/common/ToastProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ko'>
      <body className='bg-white-100'>
        <Providers>
          <div>{children}</div>
          <ToastProvider />
        </Providers>
      </body>
    </html>
  );
}
